interface LegalEntityType {
  code: number
  description: string
}

export const legalEntityTypes: Record<number, LegalEntityType> = {
  1: { code: 1, description: 'Individual' },
  2: { code: 2, description: 'Partnership' },
  3: { code: 3, description: 'Corporation' },
  4: { code: 4, description: 'Joint Ownership' },
  5: { code: 5, description: 'Joint Venture' },
  6: { code: 6, description: 'Association Incorporated' },
  7: { code: 7, description: 'Association Unincorporated' },
  8: { code: 8, description: 'Trustee' },
  9: { code: 9, description: 'Joint Stock Company' },
  10: { code: 10, description: 'Limited Liability Joint Stock' },
  11: { code: 11, description: 'Company' },
  12: { code: 12, description: 'Foundation' },
  13: { code: 13, description: 'Limited Partnership' },
  14: { code: 14, description: 'State Agency' },
  15: { code: 15, description: 'Federal Agency' },
  16: { code: 16, description: 'Limited Liability Company' },
  17: { code: 17, description: 'Trust' },
  18: { code: 18, description: 'Estate' },
  19: { code: 19, description: 'Sole Proprietorship' },
  20: { code: 20, description: 'Limited Liability Limited Partnership' },
  21: { code: 21, description: 'Limited Liability Partnership' },
  22: { code: 22, description: 'Limited Corporation' },
  23: { code: 23, description: 'Partnership Limited By Shares' },
  24: { code: 24, description: 'Private Limited Company' },
  25: { code: 25, description: 'Aktiengesellschaft (AG)' },
  26: { code: 26, description: 'Besloten Vennootschap (B.V.)' },
  27: { code: 27, description: 'Gesellschaft Mit Beschränkter Haftung (GMBH)' },
  28: { code: 28, description: 'Gmbh & Co. Kg' },
  29: { code: 29, description: 'Kabushiki Kaisha (K.K.)' },
  30: { code: 30, description: 'Kommanditgesellschaft (KG)' },
  31: { code: 31, description: 'Kommanditgesellschaft Auf Aktien (KGAA)' },
  32: { code: 32, description: 'Naamloze Vennootschap (NV)' },
  33: { code: 33, description: 'Société Anonyme (SA)' },
  34: { code: 34, description: 'Société Par Actions Simplifiée (SAS)' },
  35: { code: 35, description: 'Società Per Azioni (SPA)' },
  36: { code: 36, description: 'Agency Of The United States Government' },
  37: { code: 37, description: 'Body Politic And Corporate' },
  38: { code: 38, description: 'Business Trust' },
  39: { code: 39, description: 'Charitable Corporation' },
  40: { code: 40, description: 'Charitable Trust' },
  41: { code: 41, description: 'Charitable, Non-Profit Corporation' },
  42: { code: 42, description: 'Chartered Bank' },
  43: { code: 43, description: 'Congressionally Chartered Nonprofit Organization' },
  44: { code: 44, description: 'Cooperative Association' },
  45: { code: 45, description: 'Cooperative Corporation' },
  46: { code: 46, description: 'Credit Union' },
  47: { code: 47, description: 'Federally Chartered Credit Union' },
  48: { code: 48, description: 'Federally-Recognized Indian Tribe' },
  50: { code: 50, description: 'Instrumentality' },
  51: { code: 51, description: 'Municipal Corporation' },
  52: { code: 52, description: 'National Banking Association' },
  53: { code: 53, description: 'Non-Profit Association' },
  54: { code: 54, description: 'Non-Profit Corporation' },
  55: { code: 55, description: 'Non-Profit Organization' },
  56: { code: 56, description: 'Non-Stock Corporation' },
  57: { code: 57, description: 'Professional Corporation' },
  58: { code: 58, description: 'Public Benefit Corporation' },
  59: { code: 59, description: 'State-Recognized Indian Tribe' },
  60: { code: 60, description: 'State University' },
  61: { code: 61, description: 'Stock Company' },
  62: { code: 62, description: 'Tax Exempt Corporation' },
  63: { code: 63, description: 'Allmennaksjeselskap (ASA)' },
  64: { code: 64, description: 'Aktiebolag' },
  65: { code: 65, description: 'Aktieselskab' },
  66: { code: 66, description: 'Anpartsselskab (APS)' },
  67: { code: 67, description: 'Asociación Civil' },
  68: { code: 68, description: 'Besloten Vennootschap Met Beperkte Aansprakelijkheid (BVBA)' },
  69: { code: 69, description: 'Commanditaire Vennootschap (C.V.)' },
  70: { code: 70, description: 'Compania Anonima' },
  71: { code: 71, description: 'Eingetragener Verein' },
  72: { code: 72, description: 'Exempted Limited Partnership (ELP)' },
  73: { code: 73, description: 'Fondazion' },
  74: { code: 74, description: 'Genossenschaft (GEN)' },
  75: { code: 75, description: 'Gesellschaft Burgerlichen Rechts' },
  76: { code: 76, description: 'Julkinen Osakeyhtiö' },
  77: { code: 77, description: 'Private Company Limited By Shares' },
  78: { code: 78, description: 'Private Limited Liability Company' },
  79: { code: 79, description: 'Private Unlimited Company' },
  80: { code: 80, description: 'Professional Limited Liability Company' },
  81: { code: 81, description: 'Proprietary Company' },
  82: { code: 82, description: 'Proprietary Limited Company' },
  83: { code: 83, description: 'Public Company Limited By Shares' },
  84: { code: 84, description: 'Public Limited Company' },
  85: { code: 85, description: 'Sociedad Anonima' },
  86: { code: 86, description: 'Sociedad Anónima Inscrita De Capital Abierto (S.A.I.C.A.)' },
  87: { code: 87, description: 'Sociedad De Responsabilidad Limitada' },
  88: { code: 88, description: 'Sociedade Por Ações (S.A.)' },
  89: { code: 89, description: 'Société En Commandite' },
  90: { code: 90, description: 'Societa Cooperativa (SC)' },
  91: { code: 91, description: 'Société En Nom Collectif' },
  92: { code: 92, description: 'Societá In Accomandita Semplice (SAS)' },
  93: { code: 93, description: 'Società Semplice (SS)' },
  94: { code: 94, description: 'Societas Europae (SE)' },
  95: { code: 95, description: 'Société Coopérative (SCOP)' },
  96: { code: 96, description: 'Société En Commandite Par Actions (SCA)' },
  97: { code: 97, description: 'Société En Commandite (SC)' },
  98: { code: 98, description: 'Unknown' },
  99: { code: 99, description: 'Other' }
} 

