// search.ts

export const DATE_STRATEGIES = new Set([
  "filing_date",
  "registration_date",
  "cancellation_date",
  "foreign_filing_date",
  "foreign_registration_date",
  "int_reg_date",
  "int_pub_date",
  "auto_protection_date",
  "published_opposition_date",
  "renewal_date",
  "international_renewal_date",
  "foreign_renewal_date",
]);

export const BOOLEAN_STRATEGIES = new Set([
  "section_12c",
  "section_8",
  "section_15",
  "no_current_basis",
  "no_initial_basis",
  "change_registration",
  "concurrent_use",
  "concurrent_use_proceeding",
  "name_change",
  "color_drawing",
  "three_d_drawing",
  "prior_registration_present",
  "standard_character_claim",
  "acquired_distinctiveness_whole",
  "acquired_distinctiveness_part",
  "certification_mark",
  "collective_membership_mark",
  "collective_trademark",
  "collective_service_mark",
  "trademark",
  "service_mark",
  "intent_to_use",
  "actual_use",
  "foreign_application",
  "foreign_registration",
  "extension_protection",
  "supplemental_register",
  "principal_register",
  "amended_44d_application",
  "amended_44e_application",
  "amended_66a_application",
  "current_44d",
  "current_44e",
  "current_66a",
  "current_no_basis",
  "without_basis_currently",
  "foreign_priority",
]); 