interface StatusCode {
  code: string;
  status: 'Live' | 'Dead' | 'Indifferent';
  description: string;
}

export const statusCodes: Record<string, StatusCode> = {
  '000': { code: '000', status: 'Indifferent', description: 'UNKNOWN' },
  '400': { code: '400', status: 'Dead', description: 'Dead/Cancelled - IR CANCELLED; APPLICATION PENDING TRANSFORMATION' },
  '401': { code: '401', status: 'Dead', description: 'Dead/Cancelled - IR CANCELLED - NO TRANSFORMATION FILED' },
  '402': { code: '402', status: 'Dead', description: 'Dead/Abandoned - IR CANCELLED; US APPLICATION ABANDONED' },
  '403': { code: '403', status: 'Dead', description: 'Dead/Cancelled - IR CANCELLED; REGISTRATION PENDING TRANSFORMATION' },
  '404': { code: '404', status: 'Dead', description: 'Dead/Cancelled - IR CANCELLED; US REGISTRATION CANCELLED' },
  '405': { code: '405', status: 'Dead', description: 'Dead/Cancelled - IR CANCELED; APPLICATION TRANSFRMED' },
  '406': { code: '406', status: 'Dead', description: 'Dead/Cancelled - IR CANCELLED; REGISTRATION TRANSFORMED' },
  '410': { code: '410', status: 'Live', description: 'Live/Pending - IR RESTRICTED; US APP. ABANDONED, PENDING TRANSFORMATION' },
  '411': { code: '411', status: 'Dead', description: 'Dead/Abandoned - IR RESTRICTED; US APP. ABANDONED; NO TRANSFORMATION FILED' },
  '412': { code: '412', status: 'Dead', description: 'Dead/Abandoned - IR RESTRICTED; US APPLICATION ABANDONED' },
  '413': { code: '413', status: 'Live', description: 'Live/Pending - IR RESTRICTED; US REG. CANCELLED PEND TRANSFORMATION' },
  '414': { code: '414', status: 'Dead', description: 'Dead/Cancelled - IR RESTRICTED; US REG. CANCELLED; NO TRANSFORMATION FILED' },
  '415': { code: '415', status: 'Dead', description: 'Dead/Cancelled - IR RESTRICTED; US REGISTRATION CANCELLED' },
  '416': { code: '416', status: 'Dead', description: 'Dead/Abandoned - IR RESTRICTED; US APP ABANDONED; US APP TRANSFORMED' },
  '417': { code: '417', status: 'Dead', description: 'Dead/Cancelled - IR RESTRICTED; US REG CANCELLED; US REG TRANSFORMED' },
  '600': { code: '600', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - INCOMPLETE RESPONSE' },
  '601': { code: '601', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - EXPRESS' },
  '602': { code: '602', status: 'Dead', description: 'Dead/Abandoned - ABANDONED-FAILURE TO RESPOND OR LATE RESPONSE' },
  '603': { code: '603', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - AFTER EX PARTE APPEAL' },
  '604': { code: '604', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - AFTER INTER-PARTES DECISION' },
  '605': { code: '605', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - EXPRESS AFTER PUB' },
  '606': { code: '606', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - NO STATEMENT OF USE FILED' },
  '607': { code: '607', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - DEFECTIVE STATEMENT OF USE' },
  '608': { code: '608', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - AFTER PETITION DECISION' },
  '609': { code: '609', status: 'Dead', description: 'Dead/Abandoned - ABANDONED - DEFECTIVE DIVIDED APPLICATION' },
  '610': { code: '610', status: 'Dead', description: 'Dead - TERMINATED AFTER SANCTIONS' },
  '612': { code: '612', status: 'Dead', description: 'Dead/Abandoned - PETITION TO REVIVE-RECEIVED' },
  '614': { code: '614', status: 'Dead', description: 'Dead/Abandoned - ABANDONED PETITION TO REVIVE-DENIED' },
  '616': { code: '616', status: 'Live', description: 'Live/Pending - REVIVED - AWAITING FURTHER ACTION' },
  '618': { code: '618', status: 'Dead', description: 'Dead/Abandoned - ABANDONED FILE - BACKFILE' },
  '620': { code: '620', status: 'Live', description: 'Live/Pending - BACKFILE APPLICATION ADDED TO DATA BASE - STATUS NOT RECORDED' },
  '622': { code: '622', status: 'Indifferent', description: 'MISASSIGNED SERIAL NUMBER' },
  '624': { code: '624', status: 'Live', description: 'Live/Registered - REGISTERED - BACKFILE' },
  '625': { code: '625', status: 'Live', description: 'Live/Registered - REGISTRATION ADDED TO THE DATA BASE-STATUS UNCLEAR' },
  '626': { code: '626', status: 'Dead', description: 'Dead/Cancelled - REGISTERED - BACKFILE CANCELLED OR EXPIRED' },
  '630': { code: '630', status: 'Live', description: 'Live/Pending - NEW APPLICATION - RECORD INITIALIZED NOT ASSIGNED TO EXAMINER' },
  '631': { code: '631', status: 'Live', description: 'Live/Pending - NEW APPLICATION - DIVIDED - INITIAL PROCESSING' },
  '632': { code: '632', status: 'Dead', description: 'Dead - INFORMAL APPLICATION' },
  '638': { code: '638', status: 'Live', description: 'Live/Pending - NEW APPLICATION - ASSIGNED TO EXAMINER' },
  '640': { code: '640', status: 'Live', description: 'Live/Pending - NON-FINAL ACTION COUNTED - NOT MAILED' },
  '641': { code: '641', status: 'Live', description: 'Live/Pending - NON-FINAL ACTION - MAILED' },
  '642': { code: '642', status: 'Live', description: 'Live/Pending - INVENTORIED AS REJECTED' },
  '643': { code: '643', status: 'Live', description: 'Live/Pending - PREVIOUS ACTION/ALLOWANCE COUNT WITHDRAWN' },
  '644': { code: '644', status: 'Live', description: 'Live/Pending - FINAL REFUSAL COUNTED - NOT MAILED' },
  '645': { code: '645', status: 'Live', description: 'Live/Pending - FINAL REFUSAL - MAILED' },
  '646': { code: '646', status: 'Live', description: 'Live/Pending - EXAMINERS AMENDMENT COUNTED - NOT MAILED' },
  '647': { code: '647', status: 'Live', description: 'Live/Pending - EXAMINERS AMENDMENT - MAILED' },
  '648': { code: '648', status: 'Live', description: 'Live/Pending - ACTION CONTINUING FINAL COUNTED - NOT MAILED' },
  '649': { code: '649', status: 'Live', description: 'Live/Pending - ACTION CONTINUING FINAL - MAILED' },
  '650': { code: '650', status: 'Live', description: 'Live/Pending - SUSPENSION INQUIRY COUNTED - NOT MAILED' },
  '651': { code: '651', status: 'Live', description: 'Live/Pending - SUSPENSION INQUIRY - MAILED' },
  '652': { code: '652', status: 'Live', description: 'Live/Pending - SUSPENSION LETTER COUNTED - NOT MAILED' },
  '653': { code: '653', status: 'Live', description: 'Live/Pending - SUSPENSION LETTER - MAILED' },
  '654': { code: '654', status: 'Live', description: 'Live/Pending - REPORT COMPLETED SUSPENSION CHECK - CASE STILL SUSPENDED' },
  '655': { code: '655', status: 'Live', description: 'Live/Pending - EXAMINER\'S AMENDMENT/PRIORITY ACTION COUNTED NOT MAILED' },
  '656': { code: '656', status: 'Live', description: 'Live/Pending - EXAMINER\'S AMENDMENT/PRIORITY ACTION MAILED' },
  '657': { code: '657', status: 'Live', description: 'Live/Pending - PRIORITY ACTION COUNTED NOT MAILED' },
  '658': { code: '658', status: 'Live', description: 'Live/Pending - PRIORITY ACTION MAILED' },
  '659': { code: '659', status: 'Live', description: 'Live/Pending - SUBSEQUENT FINAL REFUSAL COUNTED NOT MAILED' },
  '660': { code: '660', status: 'Live', description: 'Live/Pending - SUBSEQUENT FINAL MAILED' },
  '661': { code: '661', status: 'Live', description: 'Live/Pending - RESPONSE AFTER NON-FINAL ACTION - ENTERED' },
  '663': { code: '663', status: 'Live', description: 'Live/Pending - RESPONSE AFTER FINAL REJECTION - ENTERED' },
  '664': { code: '664', status: 'Live', description: 'Live/Pending - INVENTORIED AS AMENDED' },
  '665': { code: '665', status: 'Live', description: 'Live/Pending - NOTICE OF UNRESPONSIVE AMENDMENT - COUNTED' },
  '666': { code: '666', status: 'Live', description: 'Live/Pending - NOTICE OF UNRESPONSIVE AMENDMENT - MAILED' },
  '667': { code: '667', status: 'Live', description: 'Live/Pending - REFUSAL WITHDRAWL LETTER - COUNTED' },
  '668': { code: '668', status: 'Live', description: 'Live/Pending - REFUSAL WITHDRAWL LETTER - MAILED' },
  '672': { code: '672', status: 'Live', description: 'Live/Pending - REINSTATED - AWAITING FURTHER ACTION' },
  '680': { code: '680', status: 'Live', description: 'Live/Pending - APPROVED FOR PUBLICATION' },
  '681': { code: '681', status: 'Live', description: 'Live/Pending - PUBLICATION/ISSUE REVIEW COMPLETE' },
  '682': { code: '682', status: 'Live', description: 'Live/Pending - ADDITIONAL REVIEW COMPLETED - RETURNED TO PUB CYCLE' },
  '686': { code: '686', status: 'Live', description: 'Live/Pending - PUBLISHED FOR OPPOSITION' },
  '688': { code: '688', status: 'Live', description: 'Live/Pending - NOTICE OF ALLOWANCE - ISSUED' },
  '689': { code: '689', status: 'Live', description: 'Live/Pending - NOTICE OF ALLOWANCE - WITHDRAWN' },
  '690': { code: '690', status: 'Live', description: 'Live/Pending - NOTICE OF ALLOWANCE - CANCELLED' },
  '692': { code: '692', status: 'Live', description: 'Live/Pending - WITHDRAWN BEFORE PUBLICATION' },
  '693': { code: '693', status: 'Live', description: 'Live/Pending - WITHDRAWN FROM ISSUE-JURISDICTION RESTORED' },
  '694': { code: '694', status: 'Live', description: 'Live/Pending - WITHDRAWN BEFORE ISSUE' },
  '700': { code: '700', status: 'Live', description: 'Live/Registered - REGISTERED' },
  '701': { code: '701', status: 'Live', description: 'Live/Registered - SECTION 8-ACCEPTED' },
  '702': { code: '702', status: 'Live', description: 'Live/Registered - SECTION 8 & 15-ACCEPTED AND ACKNOWLEDGED' },
  '703': { code: '703', status: 'Live', description: 'Live/Registered - SECTION 15-ACKNOWLEDGED' },
  '704': { code: '704', status: 'Live', description: 'Live/Registered - PARTIAL SECTION 8 ACCEPTED' },
  '705': { code: '705', status: 'Live', description: 'Live/Registered - PARTIAL SECTION 8 & 15 ACCEPTED AND ACKNOWLEDGED' },
  '706': { code: '706', status: 'Live', description: 'Live/Registered - SECTION 71 ACCEPTED' },
  '707': { code: '707', status: 'Live', description: 'Live/Registered - PARTIAL SECTION 71 ACCEPTED' },
  '708': { code: '708', status: 'Live', description: 'Live/Registered - PARTIAL SECTION 71 & 15 ACCEPTED AND ACKNOWLEDGED' },
  '709': { code: '709', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 71' },
  '710': { code: '710', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 8' },
  '711': { code: '711', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 7' },
  '712': { code: '712', status: 'Dead', description: 'Dead/Cancelled - CANCELLED BY COURT ORDER (SECTION 37)' },
  '713': { code: '713', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 18' },
  '714': { code: '714', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 24' },
  '715': { code: '715', status: 'Indifferent', description: 'Indifferent/Cancelled - CANCELLED - RESTORED TO PENDENCY' },
  '717': { code: '717', status: 'Live', description: 'Live - REGISTERED - AWAITING DIVISIONAL FEE' },
  '718': { code: '718', status: 'Live', description: 'Live/Pending - REQUEST FOR FIRST EXTENSION - FILED' },
  '719': { code: '719', status: 'Live', description: 'Live/Pending - REQUEST FOR SECOND EXTENSION - FILED' },
  '720': { code: '720', status: 'Live', description: 'Live/Pending - REQUEST FOR THIRD EXTENSION - FILED' },
  '721': { code: '721', status: 'Live', description: 'Live/Pending - REQUEST FOR FOURTH EXTENSION - FILED' },
  '722': { code: '722', status: 'Live', description: 'Live/Pending - REQUEST FOR FIFTH EXTENSION - FILED' },
  '724': { code: '724', status: 'Live', description: 'Live/Pending - EXTENSION REQUEST REFUSAL - COUNTED' },
  '725': { code: '725', status: 'Live', description: 'Live/Pending - EXTENSION REQUEST REFUSAL - MAILED' },
  '730': { code: '730', status: 'Live', description: 'Live/Pending - FIRST EXTENSION - GRANTED' },
  '731': { code: '731', status: 'Live', description: 'Live/Pending - SECOND EXTENSION - GRANTED' },
  '732': { code: '732', status: 'Live', description: 'Live/Pending - THIRD EXTENSION - GRANTED' },
  '733': { code: '733', status: 'Live', description: 'Live/Pending - FOURTH EXTENSION - GRANTED' },
  '734': { code: '734', status: 'Live', description: 'Live/Pending - FIFTH EXTENSION - GRANTED' },
  '739': { code: '739', status: 'Live', description: 'Live/Registered - Section 71 & 15 - ACCEPTED AND ACKNOWLEDGED' },
  '740': { code: '740', status: 'Live', description: 'Live/Pending - POST REGISTRATION PAPER FILED - ASSIGNED TO PARA-LEGAL' },
  '744': { code: '744', status: 'Live', description: 'Live/Pending - STATEMENT OF USE - FILED' },
  '745': { code: '745', status: 'Live', description: 'Live/Pending - STATEMENT OF USE - INFORMAL-LETTER MAILED' },
  '746': { code: '746', status: 'Live', description: 'Live/Pending - STATEMENT OF USE - INFORMAL-RESPONSE ENTERED' },
  '748': { code: '748', status: 'Live', description: 'Live/Pending - STATEMENT OF USE - TO EXAMINER' },
  '752': { code: '752', status: 'Live', description: 'Live/Pending - SU - EXAMINER STATEMENT COUNTED - NOT MAILED' },
  '753': { code: '753', status: 'Live', description: 'Live/Pending - SU - EXAMINER STATEMENT - MAILED' },
  '756': { code: '756', status: 'Live', description: 'Live/Pending - EXAMINER STATEMENT COUNTED - NOT MAILED' },
  '757': { code: '757', status: 'Live', description: 'Live/Pending - EXAMINER STATEMENT - MAILED' },
  '760': { code: '760', status: 'Live', description: 'Live/Pending - EX PARTE APPEAL PENDING' },
  '762': { code: '762', status: 'Live', description: 'Live/Pending - EX PARTE APPEAL TERMINATED' },
  '763': { code: '763', status: 'Live', description: 'Live/Pending - EX PARTE APPEAL-REFUSAL AFFIRMED' },
  '764': { code: '764', status: 'Live', description: 'Live/Pending - EX PARTE APPEAL DISMISSED AS MOOT' },
  '765': { code: '765', status: 'Live', description: 'Live/Pending - CONCURRENT USE PROCEEDING TERMINATED-GRANTED' },
  '766': { code: '766', status: 'Live', description: 'Live/Pending - CONCURRENT USE PROCEEDING TERMINATED-DENIED' },
  '771': { code: '771', status: 'Live', description: 'Live/Pending - CONCURRENT USE PROCEEDING PENDING' },
  '772': { code: '772', status: 'Live', description: 'Live/Pending - INTERFERENCE PROCEEDING PENDING' },
  '773': { code: '773', status: 'Live', description: 'Live/Pending - EXTENSION OF TIME TO OPPOSE PROCESS - TERMINATED' },
  '774': { code: '774', status: 'Live', description: 'Live/Pending - OPPOSITION PENDING' },
  '775': { code: '775', status: 'Live', description: 'Live/Pending - OPPOSITION DISMISSED' },
  '777': { code: '777', status: 'Live', description: 'Live/Pending - OPPOSITION TERMINATED-SEE TTAB RECORDS' },
  '778': { code: '778', status: 'Live', description: 'Live/Registered - CANCELLATION DISMISSED' },
  '779': { code: '779', status: 'Live', description: 'Live/Pending - OPPOSITION SUSTAINED' },
  '780': { code: '780', status: 'Live', description: 'Live/Registered - CANCELLATION TERMINATED - SEE TTAB RECORDS' },
  '781': { code: '781', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 16A' },
  '782': { code: '782', status: 'Dead', description: 'Dead/Cancelled - CANCELLED - SECTION 16B' },
  '790': { code: '790', status: 'Live', description: 'Live/Registered - CANCELLATION PENDING' },
  '794': { code: '794', status: 'Live', description: 'Live/Pending - JURISDICTION RESTORED TO EXAMINING ATTORNEY' },
  '800': { code: '800', status: 'Live', description: 'Live/Registered - REGISTERED AND RENEWED' },
  '801': { code: '801', status: 'Live', description: 'Live/Pending - OPPOSITION PAPERS FILED' },
  '802': { code: '802', status: 'Live', description: 'Live/Pending - REQUEST FOR EXTENSION OF TIME TO FILE OPPOSITION' },
  '803': { code: '803', status: 'Live', description: 'Live/Pending - AMENDMENT AFTER PUBLICATION' },
  '804': { code: '804', status: 'Live', description: 'Live/Pending - APPEAL RECEIVED AT TTAB' },
  '806': { code: '806', status: 'Live', description: 'Live/Pending - SU - NON-FINAL ACTION COUNTED - NOT MAILED' },
  '807': { code: '807', status: 'Live', description: 'Live/Pending - SU - NON-FINAL ACTION - MAILED' },
  '808': { code: '808', status: 'Live', description: 'Live/Pending - SU - FINAL REFUSAL COUNTED - NOT MAILED' },
  '809': { code: '809', status: 'Live', description: 'Live/Pending - SU - FINAL REFUSAL - MAILED' },
  '810': { code: '810', status: 'Live', description: 'Live/Pending - SU - EXAMINER\'S AMENDMENT COUNTED - NOT MAILED' },
  '811': { code: '811', status: 'Live', description: 'Live/Pending - SU - EXAMINER\'S AMENDMENT - MAILED' },
  '812': { code: '812', status: 'Live', description: 'Live/Pending - SU - ACTION CONTINUING FINAL COUNTED - NOT MAILED' },
  '813': { code: '813', status: 'Live', description: 'Live/Pending - SU - ACTION CONTINUING FINAL - MAILED' },
  '814': { code: '814', status: 'Live', description: 'Live/Pending - SU - RESPONSE AFTER NON-FINAL ACTION - ENTERED' },
  '815': { code: '815', status: 'Live', description: 'Live/Pending - SU - RESPONSE AFTER FINAL REJECTION - ENTERED' },
  '816': { code: '816', status: 'Live', description: 'Live/Pending - SU - NOTICE OF UNRESPONSIVE AMENDMENT - COUNTED' },
  '817': { code: '817', status: 'Live', description: 'Live/Pending - SU - NOTICE OF UNRESPONSIVE AMENDMENT - MAILED' },
  '818': { code: '818', status: 'Live', description: 'Live/Pending - SU - STATEMENT OF USE ACCEPTED - APPROVED FOR REGISTRATION' },
  '819': { code: '819', status: 'Live', description: 'Live/Pending - SU - REGISTRATION REVIEW COMPLETE' },
  '820': { code: '820', status: 'Live', description: 'Live/Pending - SU-EXAMINER\'S AMENDMENT/PRIORITY ACTION COUNTED NOT MAILED' },
  '821': { code: '821', status: 'Live', description: 'Live/Pending - SU - EXAMINER\'S AMENDMENT/PRIORITY ACTION MAILED' },
  '822': { code: '822', status: 'Live', description: 'Live/Pending - SU - PRIORITY ACTION COUNTED NOT MAILED' },
  '823': { code: '823', status: 'Live', description: 'Live/Pending - SU - PRIORITY ACTION MAILED' },
  '824': { code: '824', status: 'Live', description: 'Live/Pending - SU - SUBSEQUENT FINAL REFUSAL WRITTEN' },
  '825': { code: '825', status: 'Live', description: 'Live/Pending - SU - SUBSEQUENT FINAL MAILED' },
  '900': { code: '900', status: 'Dead', description: 'Dead/Expired - EXPIRED' },
  '901': { code: '901', status: 'Dead', description: 'Dead - DEAD INVENTORIED AS REJECTED' },
  '968': { code: '968', status: 'Dead', description: 'Dead - NON REGISTRATION DATA WITHDRAWN' },
  '969': { code: '969', status: 'Live', description: 'Live/Pending - NON REGISTRATION DATA' },
  '970': { code: '970', status: 'Indifferent', description: 'RECORD CREATED DUE TO ASSIGNMENT REQUEST' },
  '973': { code: '973', status: 'Live', description: 'Live/Pending - SUSPENDED PENDING ADMINISTRATIVE REVIEW' }
};
